// =============================================================================
// 간다GO · 강원도 지역 DB
// -----------------------------------------------------------------------------
// 18개 시·군 + 7대 광역 생활권 + 이용 장소 + 예약 전 확인 페이지 정의.
// 각 지역은 실제 생활권/역/숙소 속성을 가지며, 렌더러가 이 속성을 조합해
// 지역마다 다른 본문을 생성한다(지역명만 바꾼 복붙 금지).
// =============================================================================

// ---- 7대 광역 생활권 ----
export const AREAS = [
  {
    slug: "chuncheon-hongcheon",
    name: "춘천·홍천권",
    title: "춘천·홍천권 출장마사지｜명동·온의·비발디파크 생활권 안내",
    desc: "춘천 명동·온의·석사, 홍천 비발디파크 인접권 숙소 이용 기준 안내.",
    h1: "춘천·홍천권 출장마사지 · 도심 생활권과 리조트 숙소 안내",
    type: "city",
    includes: ["춘천", "홍천", "가평·양평 인접권"],
    zones: ["춘천 명동·중앙로", "온의·퇴계", "석사·후평", "춘천역·남춘천역", "홍천읍", "비발디파크 인접권"],
    cities: ["chuncheon-si", "hongcheon-gun"],
  },
  {
    slug: "wonju-hoengseong",
    name: "원주·횡성권",
    title: "원주·횡성권 출장마사지｜무실·혁신도시·웰리힐리 안내",
    desc: "원주 무실·반곡·혁신도시, 횡성 둔내·웰리힐리 숙소 이용 기준 안내.",
    h1: "원주·횡성권 출장마사지 · 혁신도시·기업도시 이용 기준",
    type: "city",
    includes: ["원주", "횡성"],
    zones: ["무실·단계", "반곡·혁신도시", "기업도시", "원주역", "문막", "횡성읍", "둔내·웰리힐리 인접권"],
    cities: ["wonju-si", "hoengseong-gun"],
  },
  {
    slug: "gangneung-donghae-samcheok",
    name: "강릉·동해·삼척권",
    title: "강릉·동해·삼척권 출장마사지｜경포·묵호·쏠비치 안내",
    desc: "강릉 경포·안목, 동해 묵호, 삼척 쏠비치 인접 해안 숙소 이용 기준.",
    h1: "강릉·동해·삼척권 출장마사지 · 동해안 중부 해안 숙소 안내",
    type: "coastal",
    includes: ["강릉", "동해", "삼척"],
    zones: ["강릉 교동·유천", "강릉역·경포", "주문진", "동해 천곡·묵호", "삼척 교동·쏠비치 인접권", "동해항·삼척항 인접권"],
    cities: ["gangneung-si", "donghae-si", "samcheok-si"],
  },
  {
    slug: "sokcho-yangyang-goseong",
    name: "속초·양양·고성권",
    title: "속초·양양·고성권 출장마사지｜대포항·낙산·화진포 안내",
    desc: "속초 대포항·설악동, 양양 낙산·인구, 고성 토성 해안 숙소 기준 안내.",
    h1: "속초·양양·고성권 출장마사지 · 동해안 북부 해안 숙소 안내",
    type: "coastal",
    includes: ["속초", "양양", "고성"],
    zones: ["속초 중앙시장·조양", "대포항·속초해변", "설악동", "양양 낙산·인구", "고성 토성·간성", "동해안 펜션·리조트권"],
    cities: ["sokcho-si", "yangyang-gun", "goseong-gun"],
  },
  {
    slug: "pyeongchang-jeongseon-taebaek",
    name: "평창·정선·태백권",
    title: "평창·정선·태백권 출장마사지｜용평·하이원·황지 안내",
    desc: "평창 대관령·용평, 정선 고한·하이원, 태백 황지 리조트 숙소 기준.",
    h1: "평창·정선·태백권 출장마사지 · 산악 리조트 숙소 이용 기준",
    type: "resort",
    includes: ["평창", "정선", "태백"],
    zones: ["평창 대관령·용평", "봉평·휘닉스파크", "정선 고한·사북", "하이원 리조트 인접권", "태백 황지·장성", "산악 관광 숙소권"],
    cities: ["pyeongchang-gun", "jeongseon-gun", "taebaek-si"],
  },
  {
    slug: "cheorwon-hwacheon-yanggu-inje",
    name: "철원·화천·양구·인제권",
    title: "철원·화천·양구·인제권 출장마사지｜접경·외곽 이동 기준",
    desc: "철원·화천·양구·인제 접경권 주소·외곽 이동·예약 시간 확인 기준 안내.",
    h1: "철원·화천·양구·인제권 출장마사지 · 접경·외곽 이동 기준 안내",
    type: "border",
    includes: ["철원", "화천", "양구", "인제"],
    zones: ["철원 동송·갈말", "화천읍", "양구읍", "인제읍·원통", "군부대 인접 생활권", "접경·외곽 이동권"],
    cities: ["cheorwon-gun", "hwacheon-gun", "yanggu-gun", "inje-gun"],
  },
  {
    slug: "yeongwol-south-inland",
    name: "영월·남부 내륙권",
    title: "영월·남부 내륙권 출장마사지｜동강·내륙 숙소 이동 기준",
    desc: "영월읍·주천, 동강 관광 숙소, 제천 인접 내륙권 이동 기준 안내.",
    h1: "영월·남부 내륙권 출장마사지 · 내륙 관광 숙소 이동 기준",
    type: "inland",
    includes: ["영월", "정선 일부", "평창 남부", "제천 인접권"],
    zones: ["영월읍", "주천·쌍용", "제천 인접권", "동강 관광 숙소", "내륙 펜션·캠핑 숙소권"],
    cities: ["yeongwol-gun"],
  },
];

// ---- 18개 시·군 ----
// tier: 1 = 1차 우선 색인, 2 = 2차(얇게 시작, 상위 생활권 연결)
export const CITIES = [
  {
    slug: "chuncheon-si", name: "춘천시", area: "chuncheon-hongcheon", type: "city", tier: 1,
    title: "춘천 출장마사지｜명동·온의·춘천역 생활권 안내",
    desc: "춘천 명동·온의·석사·춘천역 도심 생활권과 숙소 이용 기준 안내.",
    h1: "춘천 출장마사지 · 명동·온의·춘천역 생활권 안내",
    zones: ["명동·중앙로", "온의·퇴계", "석사·후평", "춘천역·남춘천역"],
    stations: ["춘천역", "남춘천역", "춘천터미널"],
    stay: ["hotel", "officetel", "apartment-home"],
  },
  {
    slug: "wonju-si", name: "원주시", area: "wonju-hoengseong", type: "city", tier: 1,
    title: "원주 출장마사지｜무실·단계·혁신도시 이용 기준",
    desc: "원주 무실·단계·반곡 혁신도시·기업도시·원주역 숙소 이용 기준 안내.",
    h1: "원주 출장마사지 · 무실·단계·혁신도시 이용 기준",
    zones: ["무실·단계", "반곡·혁신도시", "기업도시", "원주역·문막"],
    stations: ["원주역", "만종역", "원주터미널"],
    stay: ["hotel", "officetel", "apartment-home"],
  },
  {
    slug: "gangneung-si", name: "강릉시", area: "gangneung-donghae-samcheok", type: "coastal", tier: 1,
    title: "강릉 출장마사지｜강릉역·경포·안목 숙소 안내",
    desc: "강릉 교동·경포·안목·주문진 해안 관광 숙소와 강릉역 인접 이용 기준.",
    h1: "강릉 출장마사지 · 강릉역·경포·안목 숙소 안내",
    zones: ["교동·유천", "강릉역", "경포·안목", "주문진"],
    stations: ["강릉역", "정동진역", "강릉터미널"],
    stay: ["hotel", "beach-accommodation", "pension"],
  },
  {
    slug: "sokcho-si", name: "속초시", area: "sokcho-yangyang-goseong", type: "coastal", tier: 1,
    title: "속초 출장마사지｜조양·대포항·설악동 생활권 안내",
    desc: "속초 조양·교동·대포항·속초해변·설악동 해안 관광 숙소 이용 기준.",
    h1: "속초 출장마사지 · 조양·대포항·설악동 생활권 안내",
    zones: ["조양·교동", "중앙시장", "대포항·속초해변", "설악동"],
    stations: ["속초터미널"],
    stay: ["hotel", "beach-accommodation", "pension"],
  },
  {
    slug: "donghae-si", name: "동해시", area: "gangneung-donghae-samcheok", type: "coastal", tier: 1,
    title: "동해 출장마사지｜천곡·묵호·망상 해안 숙소 안내",
    desc: "동해 천곡·묵호·북평·망상 항만권 해안 숙소와 관광 숙소 이용 기준.",
    h1: "동해 출장마사지 · 천곡·묵호·망상 해안 숙소 안내",
    zones: ["천곡", "묵호·북평", "동해항", "망상"],
    stations: ["동해역", "묵호역"],
    stay: ["hotel", "beach-accommodation", "pension"],
  },
  {
    slug: "samcheok-si", name: "삼척시", area: "gangneung-donghae-samcheok", type: "coastal", tier: 1,
    title: "삼척 출장마사지｜교동·삼척해변·쏠비치 인접 안내",
    desc: "삼척 교동·정라·삼척해변·쏠비치 인접 해안 리조트 숙소 이용 기준.",
    h1: "삼척 출장마사지 · 교동·삼척해변·쏠비치 인접 안내",
    zones: ["교동·남양", "정라", "삼척해변", "쏠비치 인접권"],
    stations: ["삼척해변역"],
    stay: ["resort", "beach-accommodation", "hotel"],
  },
  {
    slug: "taebaek-si", name: "태백시", area: "pyeongchang-jeongseon-taebaek", type: "resort", tier: 1,
    title: "태백 출장마사지｜황지·장성·태백역 이동 기준 안내",
    desc: "태백 황지·장성·철암·태백역 산악 도시 관광 숙소와 겨울 이동 기준.",
    h1: "태백 출장마사지 · 황지·장성·태백역 이동 기준 안내",
    zones: ["황지", "장성·철암", "태백역"],
    stations: ["태백역"],
    stay: ["hotel", "pension", "outer-area"],
  },
  {
    slug: "hongcheon-gun", name: "홍천군", area: "chuncheon-hongcheon", type: "resort", tier: 1,
    title: "홍천 출장마사지｜비발디파크·오션월드 인접 숙소 안내",
    desc: "홍천읍·서면·비발디파크·오션월드 인접 리조트 펜션 숙소 이용 기준.",
    h1: "홍천 출장마사지 · 비발디파크·오션월드 인접 숙소 안내",
    zones: ["홍천읍", "서면", "비발디파크 인접권", "오션월드 인접권"],
    stations: [],
    stay: ["resort", "pension", "outer-area"],
  },
  {
    slug: "pyeongchang-gun", name: "평창군", area: "pyeongchang-jeongseon-taebaek", type: "resort", tier: 1,
    title: "평창 출장마사지｜대관령·용평·휘닉스파크 숙소 기준",
    desc: "평창 대관령·봉평·진부·용평·휘닉스파크 리조트 펜션 이용 기준 안내.",
    h1: "평창 출장마사지 · 리조트·펜션 숙소 이용 기준",
    zones: ["대관령", "봉평·진부", "용평", "휘닉스파크"],
    stations: ["평창역", "진부역"],
    stay: ["resort", "ski-resort", "pension"],
  },
  {
    slug: "jeongseon-gun", name: "정선군", area: "pyeongchang-jeongseon-taebaek", type: "resort", tier: 1,
    title: "정선 출장마사지｜고한·사북·하이원 인접권 안내",
    desc: "정선읍·고한·사북·하이원 인접 리조트 숙소와 산간·야간 이동 기준.",
    h1: "정선 출장마사지 · 고한·사북·하이원 인접권 안내",
    zones: ["정선읍", "고한·사북", "하이원 인접권"],
    stations: [],
    stay: ["resort", "ski-resort", "outer-area"],
  },
  {
    slug: "yangyang-gun", name: "양양군", area: "sokcho-yangyang-goseong", type: "coastal", tier: 1,
    title: "양양 출장마사지｜낙산·인구·죽도 해변 숙소 기준",
    desc: "양양읍·낙산·인구·죽도 서핑 해변권 해안 숙소·펜션 이용 기준 안내.",
    h1: "양양 출장마사지 · 낙산·인구 해안 숙소 이용 기준",
    zones: ["양양읍", "낙산", "인구·죽도", "서핑 해변권"],
    stations: [],
    stay: ["beach-accommodation", "pension", "hotel"],
  },
  {
    slug: "goseong-gun", name: "고성군", area: "sokcho-yangyang-goseong", type: "coastal", tier: 1,
    title: "고성 출장마사지｜토성·간성·화진포 숙소 이동 기준",
    desc: "고성 간성·토성·거진·화진포 동해안 북부 펜션·접경 외곽 이동 기준.",
    h1: "고성 출장마사지 · 토성·간성·화진포 숙소 안내",
    zones: ["간성", "토성", "거진·화진포", "속초 인접권"],
    stations: [],
    stay: ["pension", "beach-accommodation", "border-area"],
  },
  // ---- 2차 색인 ----
  {
    slug: "hoengseong-gun", name: "횡성군", area: "wonju-hoengseong", type: "inland", tier: 2,
    title: "횡성 출장마사지｜둔내·웰리힐리 인접 숙소 이동 기준",
    desc: "횡성읍·둔내·웰리힐리 인접 리조트 펜션 숙소와 외곽 이동 기준 안내.",
    h1: "횡성 출장마사지 · 둔내·웰리힐리 인접 이동 기준",
    zones: ["횡성읍", "둔내", "웰리힐리 인접권"],
    stations: [], stay: ["resort", "pension", "outer-area"],
  },
  {
    slug: "inje-gun", name: "인제군", area: "cheorwon-hwacheon-yanggu-inje", type: "border", tier: 2,
    title: "인제 출장마사지｜원통·접경 외곽 이동 기준 안내",
    desc: "인제읍·원통 접경권 주소 확인과 외곽 이동·예약 시간 기준 안내.",
    h1: "인제 출장마사지 · 원통·접경 외곽 이동 기준",
    zones: ["인제읍", "원통", "접경 외곽권"],
    stations: [], stay: ["outer-area", "border-area", "pension"],
  },
  {
    slug: "cheorwon-gun", name: "철원군", area: "cheorwon-hwacheon-yanggu-inje", type: "border", tier: 2,
    title: "철원 출장마사지｜동송·갈말 접경 외곽 이동 기준",
    desc: "철원 동송·갈말 접경·군부대 인접권 주소·외곽 이동·예약 시간 기준.",
    h1: "철원 출장마사지 · 동송·갈말 접경 외곽 이동 기준",
    zones: ["동송", "갈말", "접경 외곽권"],
    stations: [], stay: ["outer-area", "border-area"],
  },
  {
    slug: "hwacheon-gun", name: "화천군", area: "cheorwon-hwacheon-yanggu-inje", type: "border", tier: 2,
    title: "화천 출장마사지｜화천읍·사내 접경 외곽 이동 기준",
    desc: "화천읍·사내 접경·군부대 인접권 주소 확인과 외곽 이동 기준 안내.",
    h1: "화천 출장마사지 · 화천읍·사내 접경 외곽 이동 기준",
    zones: ["화천읍", "사내", "접경 외곽권"],
    stations: [], stay: ["outer-area", "border-area"],
  },
  {
    slug: "yanggu-gun", name: "양구군", area: "cheorwon-hwacheon-yanggu-inje", type: "border", tier: 2,
    title: "양구 출장마사지｜양구읍·국토정중앙 이동 기준",
    desc: "양구읍·국토정중앙 접경권 주소 확인과 외곽 이동·예약 시간 기준.",
    h1: "양구 출장마사지 · 양구읍·국토정중앙 이동 기준",
    zones: ["양구읍", "국토정중앙", "접경 외곽권"],
    stations: [], stay: ["outer-area", "border-area"],
  },
  {
    slug: "yeongwol-gun", name: "영월군", area: "yeongwol-south-inland", type: "inland", tier: 2,
    title: "영월 출장마사지｜영월읍·동강 숙소 이동 기준 안내",
    desc: "영월읍·주천·동강 관광 숙소와 제천 인접 내륙권 외곽 이동 기준.",
    h1: "영월 출장마사지 · 영월읍·동강 숙소 이동 기준",
    zones: ["영월읍", "주천·쌍용", "동강 관광 숙소권"],
    stations: [], stay: ["pension", "outer-area"],
  },
];

// ---- 이용 장소 페이지 ----
export const USE_PAGES = [
  { slug: "hotel", name: "호텔·숙소 이용", title: "호텔 출장마사지 이용 기준｜강원도 호텔 숙소 안내", desc: "강원도 호텔 숙소 이용 전 객실 위치·프런트·예약 시간 확인 기준 안내." },
  { slug: "pension", name: "펜션·독채 숙소 이용", title: "펜션 출장마사지 이용 기준｜강원도 독채 숙소 안내", desc: "강원도 펜션·독채 숙소 출입 방식·주차·야간 이동 확인 기준 안내." },
  { slug: "resort", name: "리조트 이용", title: "리조트 출장마사지 이용 기준｜강원도 리조트 숙소", desc: "강원도 리조트 객실 이용 규정·동 위치·예약 시간 확인 기준 안내." },
  { slug: "officetel", name: "오피스텔 이용", title: "오피스텔 출장마사지 이용 기준｜공동현관 확인", desc: "강원도 오피스텔 공동현관·동호수·관리 규정 확인 이용 기준 안내." },
  { slug: "apartment-home", name: "아파트·자택 이용", title: "아파트·자택 출장마사지 이용 기준 안내", desc: "강원도 아파트·자택 공동현관·주차·방문 주소 확인 이용 기준 안내." },
  { slug: "ktx-station", name: "KTX·터미널 인접 이용", title: "KTX·터미널 인접 출장마사지 이용 기준 안내", desc: "강릉·원주·춘천역 등 KTX·터미널 인접 숙소 이용 확인 기준 안내." },
  { slug: "beach-accommodation", name: "동해안 해안 숙소 이용", title: "동해안 해안 숙소 출장마사지 이용 기준 안내", desc: "강릉·속초·양양 동해안 해안 숙소·펜션 이용 확인 기준 안내." },
  { slug: "ski-resort", name: "스키장·리조트 이용", title: "스키장·리조트 출장마사지 이용 기준 안내", desc: "평창·정선 스키장 리조트 객실 이용·겨울 이동 확인 기준 안내." },
  { slug: "border-area", name: "군부대·접경권 인접 이용", title: "접경권 인접 출장마사지 이용 기준 안내", desc: "철원·화천·양구·인제 접경권 주소·외곽 이동 확인 기준 안내." },
  { slug: "night", name: "야간 예약", title: "야간 출장마사지 예약 기준｜강원도 야간 이동 안내", desc: "강원도 야간 예약 이동 시간·도로 상황·주소 확인 기준 안내." },
  { slug: "outer-area", name: "외곽 지역 이용", title: "외곽 지역 출장마사지 이동 기준 안내", desc: "강원도 산간·외곽 지역 이동 시간·도로·예약 확인 기준 안내." },
  { slug: "winter-road", name: "겨울철 이동 확인", title: "겨울철 이동 확인 기준｜강원도 산간 도로 안내", desc: "강원도 산간 겨울철 도로·적설·이동 시간 확인 예약 기준 안내." },
];

// ---- 예약 전 확인 페이지 ----
export const CHECK_PAGES = [
  { slug: "address", name: "방문 주소 확인", title: "방문 주소 확인 기준｜강원도 출장 예약 전 확인", desc: "예약 전 정확한 방문 주소·건물명·동호수 확인 기준 안내." },
  { slug: "building-access", name: "건물 출입 방식", title: "건물 출입 방식 확인 기준｜공동현관 안내", desc: "공동현관·엘리베이터·출입 방식 예약 전 확인 기준 안내." },
  { slug: "pension-policy", name: "펜션·독채 숙소 출입 기준", title: "펜션 출입 기준 확인｜독채 숙소 예약 전 안내", desc: "펜션·독채 숙소 출입·주차·객실 위치 예약 전 확인 기준 안내." },
  { slug: "resort-policy", name: "리조트 객실 이용 기준", title: "리조트 객실 이용 기준 확인 안내", desc: "리조트 객실 동·층 위치와 이용 규정 예약 전 확인 기준 안내." },
  { slug: "hotel-policy", name: "호텔·숙소 정책", title: "호텔 숙소 정책 확인 기준 안내", desc: "호텔 프런트·객실 정책과 방문 규정 예약 전 확인 기준 안내." },
  { slug: "officetel-rule", name: "오피스텔 관리 규정", title: "오피스텔 관리 규정 확인 기준 안내", desc: "오피스텔 공동현관·관리실 규정 예약 전 확인 기준 안내." },
  { slug: "travel-fee", name: "외곽 이동비 기준", title: "외곽 이동비 기준 확인｜강원도 이동 안내", desc: "강원도 외곽·산간 이동 거리에 따른 이동 기준 확인 안내." },
  { slug: "night-travel", name: "야간 이동 가능 여부", title: "야간 이동 가능 여부 확인 기준 안내", desc: "강원도 야간 예약 이동 가능 여부·시간 확인 기준 안내." },
  { slug: "winter-road", name: "겨울철 도로·날씨 확인", title: "겨울철 도로·날씨 확인 기준 안내", desc: "강원도 산간 겨울철 도로·적설·날씨 예약 전 확인 기준 안내." },
  { slug: "time", name: "예약 가능 시간", title: "예약 가능 시간 확인 기준 안내", desc: "강원도 예약 가능 시간대와 이동 시간 확인 기준 안내." },
  { slug: "change-policy", name: "예약 변경 기준", title: "예약 변경 기준 확인 안내", desc: "예약 변경·시간 조정 기준 예약 전 확인 안내." },
  { slug: "privacy", name: "개인정보 처리 기준", title: "개인정보 처리 기준 안내｜간다GO", desc: "예약 확인·연락에 필요한 최소 개인정보 처리 기준 안내." },
  { slug: "service-policy", name: "불법·선정적 서비스 불가 안내", title: "불법·선정적 서비스 불가 안내｜간다GO", desc: "불법·선정적 서비스는 제공·안내하지 않는 운영 기준 안내." },
  { slug: "customer-notice", name: "고객 유의사항", title: "고객 유의사항 확인 기준 안내", desc: "예약 전 고객 유의사항과 확인 절차 기준 안내." },
];

// ---- 교통 거점(역/터미널) ----
export const STATIONS = [
  { slug: "chuncheon-station", name: "춘천역", city: "chuncheon-si" },
  { slug: "namchuncheon-station", name: "남춘천역", city: "chuncheon-si" },
  { slug: "wonju-station", name: "원주역", city: "wonju-si" },
  { slug: "manjong-station", name: "만종역", city: "wonju-si" },
  { slug: "gangneung-station", name: "강릉역", city: "gangneung-si" },
  { slug: "donghae-station", name: "동해역", city: "donghae-si" },
  { slug: "mukho-station", name: "묵호역", city: "donghae-si" },
  { slug: "jeongdongjin-station", name: "정동진역", city: "gangneung-si" },
  { slug: "pyeongchang-station", name: "평창역", city: "pyeongchang-gun" },
  { slug: "jinbu-station", name: "진부역", city: "pyeongchang-gun" },
  { slug: "sokcho-terminal", name: "속초터미널", city: "sokcho-si" },
  { slug: "gangneung-terminal", name: "강릉터미널", city: "gangneung-si" },
  { slug: "wonju-terminal", name: "원주터미널", city: "wonju-si" },
  { slug: "chuncheon-terminal", name: "춘천터미널", city: "chuncheon-si" },
];

// ---- 이용 후기 (운영자 제공 실제 후기 — 페이지에 그대로 노출, 스키마와 1:1 일치) ----
export const REVIEWS = [
  { author: "탁*훈", date: "2026-07-03", rating: 5, text: "회사 회의실에서 점심시간에 받았어요. 사장님도 허락해주시고, 직원들 부러워하는 눈빛이었네요. 덕분에 오후 업무 효율이 200% 상승했어요. 회사 단체 계약도 가능하다고 해서 다음엔 팀원들 같이 받으려고요. 완전 대박 아이디어예요!" },
  { author: "희*준", date: "2026-07-02", rating: 4, text: "자취방에서 받았는데, 방이 좁아서 불편하지 않을까 걱정했어요. 그런데 접이식 매트를 가져오셔서 공간 활용을 잘 해주셨어요. 마사지도 시원했고요. 다만 제 방이 2층이라 계단 오르내리시는 게 좀 미안했네요. 그래도 잘 받았어요!" },
  { author: "억*수", date: "2026-07-01", rating: 5, text: "비즈니스 출장으로 호텔에 묵었는데, 방문 마사지가 되는지 찾아봤어요. 프론트에서도 추천해주더라고요. 호텔 룸에서 편하게 받으니까 정말 최고였어요. 출장 스트레스가 싹 풀렸고, 다음 날 미팅 때 컨디션이 너무 좋았어요. 출장 갈 때마다 이용할게요!" },
  { author: "좌*영", date: "2026-06-30", rating: 3, text: "펜션에서 가족 여행 중에 받았어요. 자연 속에서 받으니까 힐링이 두 배였어요. 그런데 관리사님이 오시는 길을 못 찾으셔서 30분이나 지각하셨어요. 마사지 자체는 괜찮았지만, 시간 낭비가 좀 아쉬웠네요." },
  { author: "강*욱", date: "2026-06-29", rating: 5, text: "군대 휴가 나왔을 때 받았어요. 훈련받고 온몸이 뻐근했는데, 관리사님이 군대에서 받는 마사지랑은 차원이 달랐어요. 특히 발바닥을 정말 시원하게 풀어주셔서 걷는 게 편해졌어요. 휴가 때마다 꼭 받을 거예요!" },
  { author: "교*현", date: "2026-06-28", rating: 4, text: "수능 시험 보고 와서 목과 어깨가 돌덩이처럼 굳었어요. 시험 끝나고 바로 예약했는데, 받는 내내 잠들 뻔했어요. 그렇게 시원한 마사지는 처음이었어요. 별 하나 뺀 이유는 수험생 할인이 있었으면 좋았을 텐데 아쉬워서요." },
  { author: "태*영", date: "2026-06-27", rating: 5, text: "세차장에서 일하는데, 하루 종일 서서 일해서 다리가 너무 아팠어요. 점심시간에 세차장 옆 휴게실에서 받았어요. 관리사님이 현장에 오셔서 바로 해주셔서 너무 편했고, 다음 날 일할 때 다리가 훨씬 가벼웠어요. 일하면서 받는 마사지 최고!" },
  { author: "순*옥", date: "2026-06-26", rating: 2, text: "미용실에서 염색하면서 같이 받았어요. 머리하는 동안 마사지 받으니까 시간도 잘 가고 좋을 줄 알았는데, 관리사님이 헤어드라이어 소리 때문에 의사소통이 잘 안 됐어요. 그리고 동시에 하려다 보니 집중도 못하시는 느낌이었어요. 비추예요." },
  { author: "유*주", date: "2026-06-25", rating: 5, text: "편의점 야간 알바하는데, 밤에 손님이 없을 때 받았어요. 편의점 뒷방에서 매트 깔고 받았는데, 이런 곳까지 와주시다니 감동이었어요. 30분만 받았는데도 피로가 싹 풀렸어요. 야간 알바생들 필수 코스!" },
  { author: "감*빈", date: "2026-06-24", rating: 4, text: "병원에 입원 중인 아버지께 선물로 보내드렸어요. 병실에서 받을 수 있다니 놀라셨고, 받고 나서 통증이 많이 완화됐다고 하셨어요. 다만 병원 방문 시 방역 수칙 때문에 절차가 좀 복잡했지만, 직원분들이 잘 도와주셨어요. 아버지가 너무 좋아하셔서 만족합니다!" },
];

// ---- 이용 요금 (예시 코스) ----
export const COURSES = [
  { name: "60분 코스", price: "90,000", min: "60분", desc: "기본 컨디션·릴랙스 케어", feature: false },
  { name: "90분 코스", price: "150,000", min: "90분", desc: "아로마 포함 추천 구성", feature: true },
  { name: "120분 코스", price: "180,000", min: "120분", desc: "전신 집중 프리미엄 케어", feature: false },
];
